package com.liferay.consumer.manager.extension.screens.model.impl;

import com.liferay.consumer.manager.extension.screens.model.Placeholder;
import com.liferay.consumer.manager.extension.screens.service.PlaceholderLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the Placeholder service. Represents a row in the &quot;CM_Screens_Placeholder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PlaceholderImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PlaceholderImpl
 * @see com.liferay.consumer.manager.extension.screens.model.Placeholder
 * @generated
 */
public abstract class PlaceholderBaseImpl extends PlaceholderModelImpl
    implements Placeholder {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a placeholder model instance should use the {@link Placeholder} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            PlaceholderLocalServiceUtil.addPlaceholder(this);
        } else {
            PlaceholderLocalServiceUtil.updatePlaceholder(this);
        }
    }
}
