package com.liferay.consumer.manager.extension.screens.model;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.StagedAuditedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the Placeholder service. Represents a row in the &quot;CM_Screens_Placeholder&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.consumer.manager.extension.screens.model.impl.PlaceholderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.consumer.manager.extension.screens.model.impl.PlaceholderImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Placeholder
 * @see com.liferay.consumer.manager.extension.screens.model.impl.PlaceholderImpl
 * @see com.liferay.consumer.manager.extension.screens.model.impl.PlaceholderModelImpl
 * @generated
 */
public interface PlaceholderModel extends BaseModel<Placeholder>,
    StagedAuditedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a placeholder model instance should use the {@link Placeholder} interface instead.
     */

    /**
     * Returns the primary key of this placeholder.
     *
     * @return the primary key of this placeholder
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this placeholder.
     *
     * @param primaryKey the primary key of this placeholder
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this placeholder.
     *
     * @return the uuid of this placeholder
     */
    @AutoEscape
    @Override
    public String getUuid();

    /**
     * Sets the uuid of this placeholder.
     *
     * @param uuid the uuid of this placeholder
     */
    @Override
    public void setUuid(String uuid);

    /**
     * Returns the placeholder ID of this placeholder.
     *
     * @return the placeholder ID of this placeholder
     */
    public long getPlaceholderId();

    /**
     * Sets the placeholder ID of this placeholder.
     *
     * @param placeholderId the placeholder ID of this placeholder
     */
    public void setPlaceholderId(long placeholderId);

    /**
     * Returns the company ID of this placeholder.
     *
     * @return the company ID of this placeholder
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this placeholder.
     *
     * @param companyId the company ID of this placeholder
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this placeholder.
     *
     * @return the user ID of this placeholder
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this placeholder.
     *
     * @param userId the user ID of this placeholder
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this placeholder.
     *
     * @return the user uuid of this placeholder
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this placeholder.
     *
     * @param userUuid the user uuid of this placeholder
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this placeholder.
     *
     * @return the user name of this placeholder
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this placeholder.
     *
     * @param userName the user name of this placeholder
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this placeholder.
     *
     * @return the create date of this placeholder
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this placeholder.
     *
     * @param createDate the create date of this placeholder
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this placeholder.
     *
     * @return the modified date of this placeholder
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this placeholder.
     *
     * @param modifiedDate the modified date of this placeholder
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the key of this placeholder.
     *
     * @return the key of this placeholder
     */
    @AutoEscape
    public String getKey();

    /**
     * Sets the key of this placeholder.
     *
     * @param key the key of this placeholder
     */
    public void setKey(String key);

    /**
     * Returns the name of this placeholder.
     *
     * @return the name of this placeholder
     */
    public String getName();

    /**
     * Returns the localized name of this placeholder in the language. Uses the default language if no localization exists for the requested language.
     *
     * @param locale the locale of the language
     * @return the localized name of this placeholder
     */
    @AutoEscape
    public String getName(Locale locale);

    /**
     * Returns the localized name of this placeholder in the language, optionally using the default language if no localization exists for the requested language.
     *
     * @param locale the local of the language
     * @param useDefault whether to use the default language if no localization exists for the requested language
     * @return the localized name of this placeholder. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
     */
    @AutoEscape
    public String getName(Locale locale, boolean useDefault);

    /**
     * Returns the localized name of this placeholder in the language. Uses the default language if no localization exists for the requested language.
     *
     * @param languageId the ID of the language
     * @return the localized name of this placeholder
     */
    @AutoEscape
    public String getName(String languageId);

    /**
     * Returns the localized name of this placeholder in the language, optionally using the default language if no localization exists for the requested language.
     *
     * @param languageId the ID of the language
     * @param useDefault whether to use the default language if no localization exists for the requested language
     * @return the localized name of this placeholder
     */
    @AutoEscape
    public String getName(String languageId, boolean useDefault);

    @AutoEscape
    public String getNameCurrentLanguageId();

    @AutoEscape
    public String getNameCurrentValue();

    /**
     * Returns a map of the locales and localized names of this placeholder.
     *
     * @return the locales and localized names of this placeholder
     */
    public Map<Locale, String> getNameMap();

    /**
     * Sets the name of this placeholder.
     *
     * @param name the name of this placeholder
     */
    public void setName(String name);

    /**
     * Sets the localized name of this placeholder in the language.
     *
     * @param name the localized name of this placeholder
     * @param locale the locale of the language
     */
    public void setName(String name, Locale locale);

    /**
     * Sets the localized name of this placeholder in the language, and sets the default locale.
     *
     * @param name the localized name of this placeholder
     * @param locale the locale of the language
     * @param defaultLocale the default locale
     */
    public void setName(String name, Locale locale, Locale defaultLocale);

    public void setNameCurrentLanguageId(String languageId);

    /**
     * Sets the localized names of this placeholder from the map of locales and localized names.
     *
     * @param nameMap the locales and localized names of this placeholder
     */
    public void setNameMap(Map<Locale, String> nameMap);

    /**
     * Sets the localized names of this placeholder from the map of locales and localized names, and sets the default locale.
     *
     * @param nameMap the locales and localized names of this placeholder
     * @param defaultLocale the default locale
     */
    public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale);

    /**
     * Returns the description of this placeholder.
     *
     * @return the description of this placeholder
     */
    public String getDescription();

    /**
     * Returns the localized description of this placeholder in the language. Uses the default language if no localization exists for the requested language.
     *
     * @param locale the locale of the language
     * @return the localized description of this placeholder
     */
    @AutoEscape
    public String getDescription(Locale locale);

    /**
     * Returns the localized description of this placeholder in the language, optionally using the default language if no localization exists for the requested language.
     *
     * @param locale the local of the language
     * @param useDefault whether to use the default language if no localization exists for the requested language
     * @return the localized description of this placeholder. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
     */
    @AutoEscape
    public String getDescription(Locale locale, boolean useDefault);

    /**
     * Returns the localized description of this placeholder in the language. Uses the default language if no localization exists for the requested language.
     *
     * @param languageId the ID of the language
     * @return the localized description of this placeholder
     */
    @AutoEscape
    public String getDescription(String languageId);

    /**
     * Returns the localized description of this placeholder in the language, optionally using the default language if no localization exists for the requested language.
     *
     * @param languageId the ID of the language
     * @param useDefault whether to use the default language if no localization exists for the requested language
     * @return the localized description of this placeholder
     */
    @AutoEscape
    public String getDescription(String languageId, boolean useDefault);

    @AutoEscape
    public String getDescriptionCurrentLanguageId();

    @AutoEscape
    public String getDescriptionCurrentValue();

    /**
     * Returns a map of the locales and localized descriptions of this placeholder.
     *
     * @return the locales and localized descriptions of this placeholder
     */
    public Map<Locale, String> getDescriptionMap();

    /**
     * Sets the description of this placeholder.
     *
     * @param description the description of this placeholder
     */
    public void setDescription(String description);

    /**
     * Sets the localized description of this placeholder in the language.
     *
     * @param description the localized description of this placeholder
     * @param locale the locale of the language
     */
    public void setDescription(String description, Locale locale);

    /**
     * Sets the localized description of this placeholder in the language, and sets the default locale.
     *
     * @param description the localized description of this placeholder
     * @param locale the locale of the language
     * @param defaultLocale the default locale
     */
    public void setDescription(String description, Locale locale,
        Locale defaultLocale);

    public void setDescriptionCurrentLanguageId(String languageId);

    /**
     * Sets the localized descriptions of this placeholder from the map of locales and localized descriptions.
     *
     * @param descriptionMap the locales and localized descriptions of this placeholder
     */
    public void setDescriptionMap(Map<Locale, String> descriptionMap);

    /**
     * Sets the localized descriptions of this placeholder from the map of locales and localized descriptions, and sets the default locale.
     *
     * @param descriptionMap the locales and localized descriptions of this placeholder
     * @param defaultLocale the default locale
     */
    public void setDescriptionMap(Map<Locale, String> descriptionMap,
        Locale defaultLocale);

    /**
     * Returns the consumer ID of this placeholder.
     *
     * @return the consumer ID of this placeholder
     */
    public long getConsumerId();

    /**
     * Sets the consumer ID of this placeholder.
     *
     * @param consumerId the consumer ID of this placeholder
     */
    public void setConsumerId(long consumerId);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public String[] getAvailableLanguageIds();

    public String getDefaultLanguageId();

    public void prepareLocalizedFieldsForImport() throws LocaleException;

    public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
        throws LocaleException;

    @Override
    public Object clone();

    @Override
    public int compareTo(
        com.liferay.consumer.manager.extension.screens.model.Placeholder placeholder);

    @Override
    public int hashCode();

    @Override
    public CacheModel<com.liferay.consumer.manager.extension.screens.model.Placeholder> toCacheModel();

    @Override
    public com.liferay.consumer.manager.extension.screens.model.Placeholder toEscapedModel();

    @Override
    public com.liferay.consumer.manager.extension.screens.model.Placeholder toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
